# Site Build Settings

# jekyll-paginate configuration
paginate:            6

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

sass:
  sass_dir: assets/css
  style: :nested

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Les gourmandises de poilux"
description:	       "un site pour gourmands, mais sans sucre ni beurre"
author:              "Poilux"

# seo informations
url: https://gourmandisesdepoilux.thoh.fr
social:
  name: Gourmandises de poilux
  links: https://www.instagram.com/gourmandises_healthy_de_poilux
lang: fr_FR

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
