# Change 'comments' to true for Disqus comments
disqus:
  comments: false 
  disqus_shortname: 'millennial-3'

menu:
- {name: 'Chocolatées', folder: 'pages', file: 'chocolat.html'}
- {name: 'A emporter', folder: 'pages', file: 'emporter.html'}
- {name: 'A partager', folder: 'pages', file: 'partager.html'}
- {name: 'A propos', folder: 'pages', file: 'about.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'instagram', link: 'https://www.instagram.com/gourmandises_healthy_de_poilux/'}
- {icon: 'rss-square', link: 'feed.xml'}

# Customize site text
pagination:
  next_page: 'Recettes plus récentes'
  previous_page: 'Recettes plus anciennes'

sharing_button_prompt: 'A partager à volonté !'

related_posts: 'Vous pourriez aussi aimer...'

post_date_prefix: 'Ecrit le'
